# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-27 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('your_taxi', '0002_order_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='has_child',
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский')], max_length=3, null=True, verbose_name='Пол'),
        ),
    ]
